---
resource_types:

- name: cf-event-type
  type: docker-image
  source:
    repository: mevansam/cf-event
    tag: latest

resources:

- name: ci-pipeline-source
  type: git
  source:
    uri: https://github.com/mevansam/cf-event-resource-type

- name: cf-event
  type: cf-event-type
  source:
    api: https://api.local.pcfdev.io
    user: admin
    password: admin
    org: pcfdev-org
    space: dev1
    skip-ssl-validation: true
    debug: true
    trace: true

jobs:

- name: app-sync
  plan:
  - get: ci-pipeline-source
  - get: cf-event
    trigger: true
  - task: copy-apps
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: mevansam/cf-cli-copy
      inputs:
      - name: ci-pipeline-source
      - name: cf-event
      run:
        path: ci-pipeline-source/example/copy-apps.sh
      params:
        CF_TARGET_API: https://api.local.pcfdev.io
        CF_TARGET_SKIP_SSL_VALIDATION: --skip-ssl-validation
        CF_TARGET_USER: admin
        CF_TARGET_PASSWORD: admin
        CF_TARGET_ORG: pcfdev-org
        CF_TARGET_SPACE: dev2
